# Generated by Django 4.0.6 on 2022-07-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('status', models.BooleanField(default=True, verbose_name='Active?')),
                ('feature', models.CharField(max_length=100, verbose_name='Feature')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('icon', models.CharField(choices=[('lni-cog', 'cog'), ('lni-leaf', 'leaf'), ('lni-user', 'Users'), ('lni-layers', 'layers'), ('lni-laptop-phone', 'laptop'), ('lni-rocket', 'Rocket')], max_length=16, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Features',
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
