# Generated by Django 4.0.6 on 2022-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_features_alter_member_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.RemoveField(
            model_name='member',
            name='instagran',
        ),
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.CharField(default='#', max_length=100, verbose_name='Instagram'),
        ),
    ]
